import json
import sys

def main():

    if len(sys.argv) == 2:

        # text_fname = sys.argv[1]  # input file given to parser

        frames_fname = sys.argv[1]  # frames file generated by parser

        # detected_frames = 'frame_results.json'  # output file explaining the output

        with open(frames_fname, 'r') as frames_file:

            print('Reading detected frames: ')
            for i, line in enumerate(frames_file):
                frame_json = json.loads(line)

                # print the tokens detected
                tokens_detected = frame_json["tokens"]

                print('\n\n=======================================================================================================')
                print('Text Tokens: ', end='')
                for t in tokens_detected:
                    print(t + " ", end='')
                print()

                # print the frames detected
                frames_detected = frame_json["frames"]  # returns a list of frames
                for f in frames_detected:   # for each frame in the list
                    target = f['target']
                    print('\nFrame: ', target['name'], ' == ', end='')

                    spans = target["spans"]     # returns a list
                    for s in spans:
                        print(s["text"] + ' ', end='')
                    print()


                    # print frame elements
                    annotation_sets = f["annotationSets"]

                    for a_s in annotation_sets:     # returns a list

                        frame_elements = a_s["frameElements"]   # returns a list of frame elements

                        for fe in frame_elements:
                            print('\tFrame Element: ', fe["name"], ' == ', end='')
                            spans = fe["spans"]     # returns a list
                            for s in spans:
                                print(s["text"] + ' ', end='')
                            print()



    else:
        print("Usage: 'python print_detected_frames.py <frames-file-name>' ")

main()